//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace knowledgeBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserComment()
        {
            this.ParentCommentId = 0;
        }
    
        public int Id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ParentCommentId { get; set; }
    
        public virtual User User { get; set; }
        public virtual KnowledgeBase KnowledgeBases { get; set; }
    }
}
